# Generated by Django 4.2.1 on 2023-05-19 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(default=380730542293, max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
