# Generated by Django 4.2.1 on 2023-05-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisementmodel_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='car_photo'),
        ),
    ]
