# Generated by Django 4.2.1 on 2023-05-17 13:05

import core.services.upload_car_photo_service
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisementmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementmodel',
            name='photo',
        ),
        migrations.CreateModel(
            name='AdvertisementPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=core.services.upload_car_photo_service.upload_to)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='advertisements.advertisementmodel')),
            ],
            options={
                'db_table': 'adverts_photo',
            },
        ),
    ]
