# Generated by Django 4.2.1 on 2023-05-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisementphotomodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='city',
            field=models.CharField(default='Kyiv', max_length=30),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='car_brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Volvo', 'Volvo'), ('Mercedes', 'Mercedes'), ('Daewoo', 'Daewoo'), ('Volkswagen', 'Volkswagen'), ('Skoda', 'Skoda'), ('Ford', 'Ford'), ('Nissan', 'Nissan'), ('Renault', 'Renault'), ('Audi', 'Audi'), ('Chevrolet', 'Chevrolet'), ('Peugeot', 'Peugeot'), ('Toyota', 'Toyota'), ('KIA', 'KIA'), ('Hyundai', 'Hyundai'), ('Lexus', 'Lexus'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Lada', 'Lada'), ('Dacia', 'Dacia'), ('Opel', 'Opel')], default='BMW', max_length=40),
        ),
    ]
