# Generated by Django 4.2.1 on 2023-05-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_alter_advertisementmodel_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
