# Generated by Django 4.2.1 on 2023-05-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_alter_advertisementmodel_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
